eval:
  initial_environment_result: {'Ouster': 0.0}
  environments: {
    'Ouster': {
      'stage_introduced': 0,
      'database_files': ['pickles/Ouster_Town1_evaluation_database.pickle'],
      'query_files': [null],
    },
    'Velodyne': {
      'stage_introduced': 1,
      'database_files': ['pickles/Velodyne_Town1_evaluation_database.pickle'],
      'query_files': [null],
    },  
  }
  world_thresh: {
    'Ouster': 10,
    'Velodyne': 10,
  }
  false_pos_thresh: {
    'Ouster': 20,
    'Velodyne': 20,
  }
  time_thresh: {
    'Ouster': 30,
    'Velodyne': 30,
  }

